version: '3.2'

services:
  db:
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-pokemons
    volumes:
      - ./mongo:/data/db
